version: '3'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/db_name
    volumes:
      - .:/app

  db:
    image: postgres:13.14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
